-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, gender, email, school_handle, is_admin, paid)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'male',
        'testuser@user.com',
        'tamu',
        FALSE,
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'female',
        'testadmin@user.com',
        'tamu',
        TRUE,
        TRUE),
        ('paiduser',
         '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
         'Paid',
         'User',
         'female',
         'paiduser@user.com',
         'tamu',
         FALSE,
         TRUE);

INSERT INTO schools (school_handle, school_name, city, state, logo_url, facebook_url, instagram_url)
VALUES ('rice', 
        'Rice University', 
        'Houston', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('tamu', 
        'Texas A&M University', 
        'College Station', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('uh', 
        'University of Houston', 
        'Houston', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('unt', 
        'University of North Texas', 
        'Denton', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('uta', 
        'University of Texas at Arlington', 
        'Arlington', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('ut', 
        'University of Texas at Austin', 
        'Austin', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utd', 
        'University of Texas at Dallas', 
        'Richardson', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utep', 
        'University of Texas at El Paso', 
        'El Paso', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utrgv', 
        'University of Texas, Rio Grande Valley', 
        'Edinburg', 
        'TX', 
        'logo', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utsa', 
        'University of Texas at San Antonio', 
        'San Antonio', 
        'TX', 
        '/logos/logo2.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/');
 
INSERT INTO competitions (competition, description, school_handle, username)
VALUES ('football', 
        'Difficult ready trip question produce produce someone.', 
        'tamu', 
        'testuser'),
       ('basketball', 
       'To much recent it reality coach decision Mr. Dog', 
       'tamu', 
       'testadmin');
